//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ReportAPI.Views.ReportDataSet {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ChatLuongThanhPhamHRCDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ChatLuongThanhPhamHRCDataSet : global::System.Data.DataSet {
        
        private ChatLuongThanhPhamHRCDataTableDataTable tableChatLuongThanhPhamHRCDataTable;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public ChatLuongThanhPhamHRCDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected ChatLuongThanhPhamHRCDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["ChatLuongThanhPhamHRCDataTable"] != null)) {
                    base.Tables.Add(new ChatLuongThanhPhamHRCDataTableDataTable(ds.Tables["ChatLuongThanhPhamHRCDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ChatLuongThanhPhamHRCDataTableDataTable ChatLuongThanhPhamHRCDataTable {
            get {
                return this.tableChatLuongThanhPhamHRCDataTable;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            ChatLuongThanhPhamHRCDataSet cln = ((ChatLuongThanhPhamHRCDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["ChatLuongThanhPhamHRCDataTable"] != null)) {
                    base.Tables.Add(new ChatLuongThanhPhamHRCDataTableDataTable(ds.Tables["ChatLuongThanhPhamHRCDataTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableChatLuongThanhPhamHRCDataTable = ((ChatLuongThanhPhamHRCDataTableDataTable)(base.Tables["ChatLuongThanhPhamHRCDataTable"]));
            if ((initTable == true)) {
                if ((this.tableChatLuongThanhPhamHRCDataTable != null)) {
                    this.tableChatLuongThanhPhamHRCDataTable.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void InitClass() {
            this.DataSetName = "ChatLuongThanhPhamHRCDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ChatLuongThanhPhamHRCDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableChatLuongThanhPhamHRCDataTable = new ChatLuongThanhPhamHRCDataTableDataTable();
            base.Tables.Add(this.tableChatLuongThanhPhamHRCDataTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private bool ShouldSerializeChatLuongThanhPhamHRCDataTable() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ChatLuongThanhPhamHRCDataSet ds = new ChatLuongThanhPhamHRCDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public delegate void ChatLuongThanhPhamHRCDataTableRowChangeEventHandler(object sender, ChatLuongThanhPhamHRCDataTableRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class ChatLuongThanhPhamHRCDataTableDataTable : global::System.Data.TypedTableBase<ChatLuongThanhPhamHRCDataTableRow> {
            
            private global::System.Data.DataColumn columnARCHIVE_DATE;
            
            private global::System.Data.DataColumn columnCA;
            
            private global::System.Data.DataColumn columnSanPham;
            
            private global::System.Data.DataColumn columnSothutu;
            
            private global::System.Data.DataColumn columnTARGET_THICK;
            
            private global::System.Data.DataColumn columnTASK_SLAB;
            
            private global::System.Data.DataColumn columnSLAB_ID;
            
            private global::System.Data.DataColumn columnSTEEL_GRADE;
            
            private global::System.Data.DataColumn columnDSC2_RAMP1;
            
            private global::System.Data.DataColumn columnDSC1_RAMP1;
            
            private global::System.Data.DataColumn columnROLL_WEIGHT_H1;
            
            private global::System.Data.DataColumn columnROLL_WEIGHT_H2;
            
            private global::System.Data.DataColumn columnROLL_WEIGHT_F1;
            
            private global::System.Data.DataColumn columnROLL_WEIGHT_F2;
            
            private global::System.Data.DataColumn columnROLL_WEIGHT_F3;
            
            private global::System.Data.DataColumn columnROLL_WEIGHT_F4;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public ChatLuongThanhPhamHRCDataTableDataTable() {
                this.TableName = "ChatLuongThanhPhamHRCDataTable";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal ChatLuongThanhPhamHRCDataTableDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected ChatLuongThanhPhamHRCDataTableDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ARCHIVE_DATEColumn {
                get {
                    return this.columnARCHIVE_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn CAColumn {
                get {
                    return this.columnCA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SanPhamColumn {
                get {
                    return this.columnSanPham;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SothutuColumn {
                get {
                    return this.columnSothutu;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TARGET_THICKColumn {
                get {
                    return this.columnTARGET_THICK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn TASK_SLABColumn {
                get {
                    return this.columnTASK_SLAB;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn SLAB_IDColumn {
                get {
                    return this.columnSLAB_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn STEEL_GRADEColumn {
                get {
                    return this.columnSTEEL_GRADE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn DSC2_RAMP1Column {
                get {
                    return this.columnDSC2_RAMP1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn DSC1_RAMP1Column {
                get {
                    return this.columnDSC1_RAMP1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ROLL_WEIGHT_H1Column {
                get {
                    return this.columnROLL_WEIGHT_H1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ROLL_WEIGHT_H2Column {
                get {
                    return this.columnROLL_WEIGHT_H2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ROLL_WEIGHT_F1Column {
                get {
                    return this.columnROLL_WEIGHT_F1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ROLL_WEIGHT_F2Column {
                get {
                    return this.columnROLL_WEIGHT_F2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ROLL_WEIGHT_F3Column {
                get {
                    return this.columnROLL_WEIGHT_F3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataColumn ROLL_WEIGHT_F4Column {
                get {
                    return this.columnROLL_WEIGHT_F4;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public ChatLuongThanhPhamHRCDataTableRow this[int index] {
                get {
                    return ((ChatLuongThanhPhamHRCDataTableRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event ChatLuongThanhPhamHRCDataTableRowChangeEventHandler ChatLuongThanhPhamHRCDataTableRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event ChatLuongThanhPhamHRCDataTableRowChangeEventHandler ChatLuongThanhPhamHRCDataTableRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event ChatLuongThanhPhamHRCDataTableRowChangeEventHandler ChatLuongThanhPhamHRCDataTableRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public event ChatLuongThanhPhamHRCDataTableRowChangeEventHandler ChatLuongThanhPhamHRCDataTableRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void AddChatLuongThanhPhamHRCDataTableRow(ChatLuongThanhPhamHRCDataTableRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public ChatLuongThanhPhamHRCDataTableRow AddChatLuongThanhPhamHRCDataTableRow(
                        string ARCHIVE_DATE, 
                        string CA, 
                        string SanPham, 
                        long Sothutu, 
                        double TARGET_THICK, 
                        decimal TASK_SLAB, 
                        string SLAB_ID, 
                        string STEEL_GRADE, 
                        double DSC2_RAMP1, 
                        double DSC1_RAMP1, 
                        string ROLL_WEIGHT_H1, 
                        string ROLL_WEIGHT_H2, 
                        string ROLL_WEIGHT_F1, 
                        string ROLL_WEIGHT_F2, 
                        string ROLL_WEIGHT_F3, 
                        string ROLL_WEIGHT_F4) {
                ChatLuongThanhPhamHRCDataTableRow rowChatLuongThanhPhamHRCDataTableRow = ((ChatLuongThanhPhamHRCDataTableRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ARCHIVE_DATE,
                        CA,
                        SanPham,
                        Sothutu,
                        TARGET_THICK,
                        TASK_SLAB,
                        SLAB_ID,
                        STEEL_GRADE,
                        DSC2_RAMP1,
                        DSC1_RAMP1,
                        ROLL_WEIGHT_H1,
                        ROLL_WEIGHT_H2,
                        ROLL_WEIGHT_F1,
                        ROLL_WEIGHT_F2,
                        ROLL_WEIGHT_F3,
                        ROLL_WEIGHT_F4};
                rowChatLuongThanhPhamHRCDataTableRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowChatLuongThanhPhamHRCDataTableRow);
                return rowChatLuongThanhPhamHRCDataTableRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                ChatLuongThanhPhamHRCDataTableDataTable cln = ((ChatLuongThanhPhamHRCDataTableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new ChatLuongThanhPhamHRCDataTableDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal void InitVars() {
                this.columnARCHIVE_DATE = base.Columns["ARCHIVE_DATE"];
                this.columnCA = base.Columns["CA"];
                this.columnSanPham = base.Columns["SanPham"];
                this.columnSothutu = base.Columns["Sothutu"];
                this.columnTARGET_THICK = base.Columns["TARGET_THICK"];
                this.columnTASK_SLAB = base.Columns["TASK_SLAB"];
                this.columnSLAB_ID = base.Columns["SLAB_ID"];
                this.columnSTEEL_GRADE = base.Columns["STEEL_GRADE"];
                this.columnDSC2_RAMP1 = base.Columns["DSC2_RAMP1"];
                this.columnDSC1_RAMP1 = base.Columns["DSC1_RAMP1"];
                this.columnROLL_WEIGHT_H1 = base.Columns["ROLL_WEIGHT_H1"];
                this.columnROLL_WEIGHT_H2 = base.Columns["ROLL_WEIGHT_H2"];
                this.columnROLL_WEIGHT_F1 = base.Columns["ROLL_WEIGHT_F1"];
                this.columnROLL_WEIGHT_F2 = base.Columns["ROLL_WEIGHT_F2"];
                this.columnROLL_WEIGHT_F3 = base.Columns["ROLL_WEIGHT_F3"];
                this.columnROLL_WEIGHT_F4 = base.Columns["ROLL_WEIGHT_F4"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            private void InitClass() {
                this.columnARCHIVE_DATE = new global::System.Data.DataColumn("ARCHIVE_DATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnARCHIVE_DATE);
                this.columnCA = new global::System.Data.DataColumn("CA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCA);
                this.columnSanPham = new global::System.Data.DataColumn("SanPham", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSanPham);
                this.columnSothutu = new global::System.Data.DataColumn("Sothutu", typeof(long), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSothutu);
                this.columnTARGET_THICK = new global::System.Data.DataColumn("TARGET_THICK", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTARGET_THICK);
                this.columnTASK_SLAB = new global::System.Data.DataColumn("TASK_SLAB", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTASK_SLAB);
                this.columnSLAB_ID = new global::System.Data.DataColumn("SLAB_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSLAB_ID);
                this.columnSTEEL_GRADE = new global::System.Data.DataColumn("STEEL_GRADE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTEEL_GRADE);
                this.columnDSC2_RAMP1 = new global::System.Data.DataColumn("DSC2_RAMP1", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDSC2_RAMP1);
                this.columnDSC1_RAMP1 = new global::System.Data.DataColumn("DSC1_RAMP1", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDSC1_RAMP1);
                this.columnROLL_WEIGHT_H1 = new global::System.Data.DataColumn("ROLL_WEIGHT_H1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROLL_WEIGHT_H1);
                this.columnROLL_WEIGHT_H2 = new global::System.Data.DataColumn("ROLL_WEIGHT_H2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROLL_WEIGHT_H2);
                this.columnROLL_WEIGHT_F1 = new global::System.Data.DataColumn("ROLL_WEIGHT_F1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROLL_WEIGHT_F1);
                this.columnROLL_WEIGHT_F2 = new global::System.Data.DataColumn("ROLL_WEIGHT_F2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROLL_WEIGHT_F2);
                this.columnROLL_WEIGHT_F3 = new global::System.Data.DataColumn("ROLL_WEIGHT_F3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROLL_WEIGHT_F3);
                this.columnROLL_WEIGHT_F4 = new global::System.Data.DataColumn("ROLL_WEIGHT_F4", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROLL_WEIGHT_F4);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public ChatLuongThanhPhamHRCDataTableRow NewChatLuongThanhPhamHRCDataTableRow() {
                return ((ChatLuongThanhPhamHRCDataTableRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ChatLuongThanhPhamHRCDataTableRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(ChatLuongThanhPhamHRCDataTableRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ChatLuongThanhPhamHRCDataTableRowChanged != null)) {
                    this.ChatLuongThanhPhamHRCDataTableRowChanged(this, new ChatLuongThanhPhamHRCDataTableRowChangeEvent(((ChatLuongThanhPhamHRCDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ChatLuongThanhPhamHRCDataTableRowChanging != null)) {
                    this.ChatLuongThanhPhamHRCDataTableRowChanging(this, new ChatLuongThanhPhamHRCDataTableRowChangeEvent(((ChatLuongThanhPhamHRCDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ChatLuongThanhPhamHRCDataTableRowDeleted != null)) {
                    this.ChatLuongThanhPhamHRCDataTableRowDeleted(this, new ChatLuongThanhPhamHRCDataTableRowChangeEvent(((ChatLuongThanhPhamHRCDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ChatLuongThanhPhamHRCDataTableRowDeleting != null)) {
                    this.ChatLuongThanhPhamHRCDataTableRowDeleting(this, new ChatLuongThanhPhamHRCDataTableRowChangeEvent(((ChatLuongThanhPhamHRCDataTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void RemoveChatLuongThanhPhamHRCDataTableRow(ChatLuongThanhPhamHRCDataTableRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ChatLuongThanhPhamHRCDataSet ds = new ChatLuongThanhPhamHRCDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "ChatLuongThanhPhamHRCDataTableDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class ChatLuongThanhPhamHRCDataTableRow : global::System.Data.DataRow {
            
            private ChatLuongThanhPhamHRCDataTableDataTable tableChatLuongThanhPhamHRCDataTable;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            internal ChatLuongThanhPhamHRCDataTableRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableChatLuongThanhPhamHRCDataTable = ((ChatLuongThanhPhamHRCDataTableDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ARCHIVE_DATE {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.ARCHIVE_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ARCHIVE_DATE\' in table \'ChatLuongThanhPhamHRCDataTable\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.ARCHIVE_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string CA {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.CAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CA\' in table \'ChatLuongThanhPhamHRCDataTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.CAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SanPham {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.SanPhamColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SanPham\' in table \'ChatLuongThanhPhamHRCDataTable\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.SanPhamColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public long Sothutu {
                get {
                    try {
                        return ((long)(this[this.tableChatLuongThanhPhamHRCDataTable.SothutuColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Sothutu\' in table \'ChatLuongThanhPhamHRCDataTable\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.SothutuColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public double TARGET_THICK {
                get {
                    try {
                        return ((double)(this[this.tableChatLuongThanhPhamHRCDataTable.TARGET_THICKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TARGET_THICK\' in table \'ChatLuongThanhPhamHRCDataTable\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.TARGET_THICKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public decimal TASK_SLAB {
                get {
                    try {
                        return ((decimal)(this[this.tableChatLuongThanhPhamHRCDataTable.TASK_SLABColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TASK_SLAB\' in table \'ChatLuongThanhPhamHRCDataTable\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.TASK_SLABColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string SLAB_ID {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.SLAB_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SLAB_ID\' in table \'ChatLuongThanhPhamHRCDataTable\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.SLAB_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string STEEL_GRADE {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.STEEL_GRADEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STEEL_GRADE\' in table \'ChatLuongThanhPhamHRCDataTable\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.STEEL_GRADEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public double DSC2_RAMP1 {
                get {
                    try {
                        return ((double)(this[this.tableChatLuongThanhPhamHRCDataTable.DSC2_RAMP1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DSC2_RAMP1\' in table \'ChatLuongThanhPhamHRCDataTable\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.DSC2_RAMP1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public double DSC1_RAMP1 {
                get {
                    try {
                        return ((double)(this[this.tableChatLuongThanhPhamHRCDataTable.DSC1_RAMP1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DSC1_RAMP1\' in table \'ChatLuongThanhPhamHRCDataTable\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.DSC1_RAMP1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ROLL_WEIGHT_H1 {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_H1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROLL_WEIGHT_H1\' in table \'ChatLuongThanhPhamHRCDataTable\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_H1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ROLL_WEIGHT_H2 {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_H2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROLL_WEIGHT_H2\' in table \'ChatLuongThanhPhamHRCDataTable\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_H2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ROLL_WEIGHT_F1 {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROLL_WEIGHT_F1\' in table \'ChatLuongThanhPhamHRCDataTable\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ROLL_WEIGHT_F2 {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROLL_WEIGHT_F2\' in table \'ChatLuongThanhPhamHRCDataTable\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ROLL_WEIGHT_F3 {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROLL_WEIGHT_F3\' in table \'ChatLuongThanhPhamHRCDataTable\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public string ROLL_WEIGHT_F4 {
                get {
                    try {
                        return ((string)(this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F4Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROLL_WEIGHT_F4\' in table \'ChatLuongThanhPhamHRCDataTable\' i" +
                                "s DBNull.", e);
                    }
                }
                set {
                    this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F4Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsARCHIVE_DATENull() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.ARCHIVE_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetARCHIVE_DATENull() {
                this[this.tableChatLuongThanhPhamHRCDataTable.ARCHIVE_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsCANull() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.CAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetCANull() {
                this[this.tableChatLuongThanhPhamHRCDataTable.CAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSanPhamNull() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.SanPhamColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSanPhamNull() {
                this[this.tableChatLuongThanhPhamHRCDataTable.SanPhamColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSothutuNull() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.SothutuColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSothutuNull() {
                this[this.tableChatLuongThanhPhamHRCDataTable.SothutuColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTARGET_THICKNull() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.TARGET_THICKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTARGET_THICKNull() {
                this[this.tableChatLuongThanhPhamHRCDataTable.TARGET_THICKColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsTASK_SLABNull() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.TASK_SLABColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetTASK_SLABNull() {
                this[this.tableChatLuongThanhPhamHRCDataTable.TASK_SLABColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSLAB_IDNull() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.SLAB_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSLAB_IDNull() {
                this[this.tableChatLuongThanhPhamHRCDataTable.SLAB_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsSTEEL_GRADENull() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.STEEL_GRADEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetSTEEL_GRADENull() {
                this[this.tableChatLuongThanhPhamHRCDataTable.STEEL_GRADEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDSC2_RAMP1Null() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.DSC2_RAMP1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDSC2_RAMP1Null() {
                this[this.tableChatLuongThanhPhamHRCDataTable.DSC2_RAMP1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsDSC1_RAMP1Null() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.DSC1_RAMP1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetDSC1_RAMP1Null() {
                this[this.tableChatLuongThanhPhamHRCDataTable.DSC1_RAMP1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsROLL_WEIGHT_H1Null() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_H1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetROLL_WEIGHT_H1Null() {
                this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_H1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsROLL_WEIGHT_H2Null() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_H2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetROLL_WEIGHT_H2Null() {
                this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_H2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsROLL_WEIGHT_F1Null() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetROLL_WEIGHT_F1Null() {
                this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsROLL_WEIGHT_F2Null() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetROLL_WEIGHT_F2Null() {
                this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsROLL_WEIGHT_F3Null() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetROLL_WEIGHT_F3Null() {
                this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public bool IsROLL_WEIGHT_F4Null() {
                return this.IsNull(this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F4Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public void SetROLL_WEIGHT_F4Null() {
                this[this.tableChatLuongThanhPhamHRCDataTable.ROLL_WEIGHT_F4Column] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
        public class ChatLuongThanhPhamHRCDataTableRowChangeEvent : global::System.EventArgs {
            
            private ChatLuongThanhPhamHRCDataTableRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public ChatLuongThanhPhamHRCDataTableRowChangeEvent(ChatLuongThanhPhamHRCDataTableRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public ChatLuongThanhPhamHRCDataTableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591